# -*- coding: utf-8 -*-

db.define_table('clients',
    Field('first_name', 'string', notnull=True),
    Field('last_name', 'string', notnull=True),
    Field('phone', 'string', length=10),
    Field('mobile', 'string', length=10),
    Field('country_id', 'reference countries', default=1),
    Field('state_id', 'reference states'),
    Field('municipality_id', 'reference municipalities'),
    Field('locality_id', 'reference localities'),
    Field('address', 'string'),
    Field('suburb', 'string'),
    Field('zip_code', 'string', length=5),
    Field('rfc', 'string', length=13, notnull=True, unique=True),
    Field('date_added', 'datetime', default=request.now),
    Field('date_modified', 'datetime', update=request.now),
    Field('added_by', 'reference auth_user',
        default=auth.user.id if auth.user else None),
    Field('modified_by', 'reference auth_user',
        update=auth.user.id if auth.user else None),
    migrate=MIGRATE)
